version: 2
jobs:
  test:
    working_directory: /go/src/github.com/b-social/terraform-provider-kafkaconnect
    docker:
    - image: golang:1.11-alpine
    steps:
    - run:
        command: apk add --no-cache git openssh-client
    - checkout
    - run: ./scripts/ci/common/install-ruby.sh
    - run: ./scripts/ci/steps/test.sh
  prerelease:
    working_directory: /go/src/github.com/b-social/terraform-provider-kafkaconnect
    docker:
    - image: golang:1.11-alpine
    steps:
    - run:
        command: apk add --no-cache git openssh-client
    - checkout
    - run: ./scripts/ci/common/install-ruby.sh
    - run: ./scripts/ci/common/configure-git.sh
    - run: ./scripts/ci/steps/prerelease.sh
  release:
    working_directory: /go/src/github.com/b-social/terraform-provider-kafkaconnect
    docker:
    - image: golang:1.11-alpine
    steps:
    - run:
        command: apk add --no-cache git openssh-client
    - checkout
    - run: ./scripts/ci/common/install-ruby.sh
    - run: ./scripts/ci/common/configure-git.sh
    - run: ./scripts/ci/steps/release.sh

workflows:
  version: 2
  pipeline:
    jobs:
    - test
    - prerelease:
        requires:
        - test
        filters:
          branches:
            only: master
    - hold:
        type: approval
        requires:
        - prerelease
        filters:
          branches:
            only: master
    - release:
        requires:
        - hold
        filters:
          branches:
            only: master
